### ISSUE TITLE
Версия модуля 1.8

### ISSUE THREAD

**Issue by klaos27** [yandex-money/yandex-money-cms-opencart#11]
Добрый день!
ocStore 1.5.5.1.2 (opencart 1.5.6)
Обновил модуль для работы по 54ФЗ
При переходе на страницу оформления заказа получаю следующее
`Parse error: syntax error, unexpected '[' in /catalog/controller/payment/yandexmoney.php on line 83`
Насколько правильно здесь не знаю, но в этой строке квадратные скобки заменил на array(); и страница оформления открылась нормально, но появилась Notice
`Notice: Undefined index: 0 in /catalog/controller/payment/yandexmoney.php on line 128`
В магазине полностью удалены налоговые классы и налоговые ставки. В настройках модуля установлено "Без НДС"

**Comment by actofgod** [comment]
В pull реквесте #12 проблемы исправлены
