### ISSUE TITLE
Модуль конфликтует с модулем Simple

### ISSUE THREAD

**Issue by Sigizmund2012** [yandex-money/yandex-money-cms-opencart#13]
Здравствуйте. Модуль Simple очень популярен http://simpleopencart.com/ и стоит на большинстве серьёзных магазинов. Сотрудник Яндекса Илья Сизов Инженер группы технического сопровождения написал, что это конфликт с Simple и разработчик от Яндекса в курсе проблемы. Не могли бы вы пофиксить баг? Обращаться к разрабу Simple смысла нет, другие-то платёжные модули работают.

**Comment by ikarmanov** [comment]
Добрый день.

Наш модуль написан для оригинальной версии Opencart. Для анализа ситуации нам необходим технический комментарий службы поддержки модуля Simpla, т.к. данный модуль меняет стандартный процесс оформления заказа.

**Comment by Sigizmund2012** [comment]
Создал pull-request. Если примете, issue можно закрыть.
