### ISSUE TITLE
Модуль не работает!

### ISSUE THREAD

**Issue by sukhanoff** [yandex-money/yandex-money-cms-opencart#14]
Добрый день! Модуль не работает, либо работает некорректно.
Все настройки прописаны, но при тестировании как в тестовой, так и в боевой среде, после выбора способа оплаты уже на стороне Яндекс и введения данных карты, показывается страницу "Что-то пошло не так", деньги списываются, а потом приходит отмена операции. checkUrl/avisoUrl прописаны правильно и в ЛК Кассы и в Opencart (они совпадают).
Сделали логирование на стороне Opencart, из него видно, что проблема возникает в том, что ответ, который отдает модуль по определенным причинам (нам неизвестным) не может быть прочитан яндексом.
![rucosmetic](https://user-images.githubusercontent.com/31533166/30782702-0845a0ba-a140-11e7-8f16-a001c8cd6c3e.png)
Это схема взаимодествия, которая выявлена в ходе логирования. Пункт 4 не работает.
Ниже примеры логов, которые видят сотрудники Яндекса:
[2017-09-20T14:10:35.893+03:00] INFO  [CommonHTTPStub] - Request params:
shopSumCurrencyPaycash=643
rebillingOn=false
orderSumBankPaycash=1001
orderNumber=1015428
orderSumAmount=10.00
orderSumCurrencyPaycash=643
shopArticleId=188061
cms_name=opencart
paymentPayerCode=42000400000002
unilabel=2154603d-000f-50a0-a000-0302ff9139c3
customerNumber=1015428 sukhanoff@hotmail.com
paymentType=AC
requestDatetime=2017-09-20T14:10:35.890+03:00
environment=Live
cps_user_country_code=RU
orderCreatedDatetime=2017-09-20T14:10:02.551+03:00
action=checkOrder
invoiceId=2000805851289
shopId=45619
scid=31483
shopSumBankPaycash=1001
shopSumAmount=9.65
md5=BDCBC57626632AEFED91E86D6117A089

[2017-09-20T14:10:36.388+03:00] INFO  [CommonHttp30Protocol] - response: '<?xml version="1.0" encoding="UTF-8"?><checkOrderResponse performedDatetime="2017-09-20T14:10:36+03:00" code="100" invoiceId="2000805851289" shopId="45619"/>'

Вот еще один, здесь код ошибки другой:
[2017-09-22T09:45:25.613+03:00] WARN  [CommonHTTPStub] - Response is not XML: response=GIF89a  �����,    D ;<?xml version="1.0" encoding="UTF-8"?><checkOrderResponse performedDatetime="2017-09-22T09:45:25+03:00" code="0" invoiceId="2000807855064" shopId="45619"/> DKTyFANbk/s=.6b0e
2017-09-22, 09:45:17.909        [CommonHTTPStub] - Request params:
orderNumber=1015461
orderSumAmount=20.00
cdd_exp_date=0520
shopArticleId=188061
cms_name=opencart
paymentPayerCode=410012393855702
cdd_rrn=
external_id=deposit
paymentType=AC
requestDatetime=2017-09-22T09:45:17.907+03:00
depositNumber=poDk5bxecN23Xx7BNckJtQ1Ife8Z.0049.201709
nst_eplPayment=true
cdd_response_code=00
cps_user_country_code=RU
orderCreatedDatetime=2017-09-22T09:45:17.710+03:00
sk=u9f3c381af22dd753b88bea41526fd225
action=checkOrder
shopId=45619
scid=31483
shopSumBankPaycash=1001
shopSumCurrencyPaycash=643
rebillingOn=false
orderSumBankPaycash=1001
orderSumCurrencyPaycash=643
merchant_order_id=1015461_220917094425_00000_45619
unilabel=2156c509-0009-5000-8000-0000265defb1
cdd_pan_mask=548442|6061
customerNumber=1015461 sukhanoff@hotmail.com
yandexPaymentId=2570048046108787
environment=Live
invoiceId=2000807855064
cdd_auth_code=305892
btnPay=Pay
shopSumAmount=19.30
md5=1CD8F0E2DF43F6304BB9DA78F01197E2

[2017-09-22T09:45:25.631+03:00] WARN  [IPWPaymentApprovalHandler] - invoiceId: 2000807855064. Техническая ошибка на стороне магазина. Попробуйте повторить платеж немного позже. Если проблемы продолжаются длительное время, обратитесь в службу поддержки, указав номер ошибки: 0023.
ru.yamoney.calypso.shops.paymentagent.ShopPaymentException: Техническая ошибка на стороне магазина. Попробуйте повторить платеж немного позже. Если проблемы продолжаются длительное время, обратитесь в службу поддержки, указав номер ошибки: 0023.

[2017-09-22T09:45:25.638+03:00] INFO  [CryptoTemplate] - Response: ConfirmAction=2;RejectResource=<?xml version="1.0" encoding="windows-1251"?>
<result>
  <type>error</type>
  <shopErrorCode>23</shopErrorCode>
  <data>
    <property name="msg">
      <promt></promt>
      <value>Техническая ошибка на стороне магазина. Попробуйте повторить платеж немного позже. Если проблемы продолжаются длительное время, обратитесь в службу поддержки, указав номер ошибки: 0023.</value>
    </property>
    <property name="shop_url">
      <value><![CDATA[https://rucosmetics.ru/index.php?route=checkout/failure&orderNumber=1015461&orderSumAmount=20.00&cdd_exp_date=0520&shopArticleId=188061&cms_name=opencart&paymentPayerCode=410012393855702&cdd_rrn=&external_id=deposit&paymentType=AC&requestDatetime=2017-09-22T09%3A45%3A25.636%2B03%3A00&depositNumber=poDk5bxecN23Xx7BNckJtQ1Ife8Z.0049.201709&nst_eplPayment=true&cdd_response_code=00&cps_user_country_code=RU&orderCreatedDatetime=2017-09-22T09%3A45%3A17.710%2B03%3A00&sk=u9f3c381af22dd753b88bea41526fd225&action=PaymentFail&shopId=45619&scid=31483&rebillingOn=false&orderSumBankPaycash=1001&orderSumCurrencyPaycash=643&merchant_order_id=1015461_220917094425_00000_45619&unilabel=2156c509-0009-5000-8000-0000265defb1&cdd_pan_mask=548442%7C6061&customerNumber=1015461+sukhanoff%40hotmail.com&yandexPaymentId=2570048046108787&environment=Live&invoiceId=2000807855064&cdd_auth_code=305892&btnPay=Pay]]></value>
    </property>
  </data>
</result>;WalletAccountData=null

**Comment by ikarmanov** [comment]
Добрый день.

Похоже на проблему кодирования страниц у вашего сайта.
