### ISSUE TITLE
Opencart 2.0

### ISSUE THREAD

**Issue by kerr** [yandex-money/yandex-money-cms-opencart#7]
когда выйдет официальный модуль для свежего Open cart???

**Comment by ikarmanov** [comment]
Добрый день.

Платежный модуль [yandex-money-cms-opencart](https://github.com/yandex-money/yandex-money-cms-opencart) создан для CMS Opencart 1.5.x. 
Для CMS Opencart 2.x существует другой модуль - [yandex-money-cms-opencart2](https://github.com/yandex-money/yandex-money-cms-opencart2)
