### ISSUE TITLE
Не изменяется статус заказа в боевом режиме

### ISSUE THREAD

**Issue by idealogica** [yandex-money/yandex-money-cms-opencart#8]
К сожалению, не изменяется статус заказа в боевом режиме. Нужно использовать withdraw_amount для сравнения сумм и вызывать  $this->model_checkout_order->confirm(...) перед update.

**Comment by idealogica** [comment]
... в классе ControllerPaymentYandexMoney папки Catalog

**Comment by ikarmanov** [comment]
Спасибо за замечания.
Мы внесли некоторые из них в версию 1.7.2
